server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studentpipeline
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 5000
          order_inserts: true
          order_updates: true
        
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

# Custom configuration
datapath:
  base: ${DATAPATH_BASE:C:/var/log/applications/API/dataprocessing}

# Logging configuration
logging:
  level:
    com.studentpipeline: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always